server:
  port: 8081 # Cổng riêng cho Auth Service

spring:
  application:
    name: auth-service
  # Cấu hình kết nối PostgreSQL (auth_db)
  datasource:
    url: jdbc:postgresql://hrm-postgres:5432/auth_db # Sử dụng service name của Docker
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  # Cấu hình JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Dùng update cho dev, dùng none cho prod
    show-sql: true
  # Cấu hình Redis
  data:
    redis:
      host: hrm-redis # Sử dụng service name của Docker
      port: 6379

  mybatis:
    mapper-locations: classpath:mapper/*.xml